### ISSUE TITLE
myst renderer should take over markdown viewer as well

### ISSUE THREAD

**Issue by tavin** [executablebooks/jupyterlab-myst#100]
### Context

This extension takes over the rendering of markdown cells in notebooks, but it seems that it does not change the rendering of markdown files opened in the jupyter lab markdown viewer.

### Proposal

If possible, the renderer in the markdown file viewer should be upgraded just as it is for markdown cells.

**Comment by rowanc1** [comment]
Thank you for the feedback, and glad you are up and running with the extension! This is certainly something we have been thinking about, and now it is officially on the list, thank you!

**Comment by tavin** [comment]
Ok @rowanc1 that's good news!

I've been doing some "A/B testing" on myself, comparing myst markdown cells (morally files) to the VS code markdown file preview afforded by [myst-vs-code](https://github.com/executablebooks/myst-vs-code). CSS tweaks became a vital concern pretty quickly, and I found that in VS code I could simply add a (relatively located) custom.css file, using the settings editor. So, I am hoping that will also be possible for jupyter lab myst file previews. That said, I can appreciate it might be well outside the scope of this enhancement request.

**Comment by tavin** [comment]
@rowanc1 @agoose77 this is tangential, but I'm not sure where else to ask the question. Is there any way to edit a markdown file using the notebook editor? Given that tools exist for converting between ipynb and notebook-as-markdown formats, one might almost expect an "open with" option for this. Would it be a matter of writing an extension to basically override the load and save routines?

**Comment by agoose77** [comment]
Yes, if you install the https://github.com/mwouts/jupytext/ extension, this "just works"!

**Comment by like101101** [comment]
Hi! The Markdowns in the RISE extension (slideshow) for the jupyter notebook are also not rendered, which they can be rendered in the previous versions of jupyterlab_myst (v0.1.*). I'm wondering if that is something related to this issue here.

**Comment by agoose77** [comment]
Are they not rendered _at all_, or just rendered as GFM Markdown instead of MyST? The latter is expected, whilst the former is not. We will eventually support dynamically generated Markdown, but in the mean-time, you should probably pin `jupyterlab-myst<1.0.0`

**Comment by like101101** [comment]
Sorry for the confusion. It is the latter. Thank you very much!

**Comment by itcarroll** [comment]
Thanks for the workaround on using MyST in RISE, @agoose77. Thanks in advance for the supporting the latest and greatest of MyST in RISE slides, when you get to it!
