### ISSUE TITLE
Breadcrumbs in file viewer modified

### ISSUE THREAD

**Issue by agoose77** [executablebooks/jupyterlab-myst#105]
### Describe the bug

![image](https://user-images.githubusercontent.com/1248413/221848247-6a622561-2476-41c0-b7ca-bb213f75ad8e.png)

### Reproduce the bug

Open JupyterLab-myst

**Comment by rowanc1** [comment]
Fixed by removing svg is a block element in the preflight css. See #117.

**Comment by rowanc1** [comment]
This will be release soon!
