### ISSUE TITLE
Some cells with inline expressions not getting rendered at random?

### ISSUE THREAD

**Issue by fperez** [executablebooks/jupyterlab-myst#107]
### Describe the bug

**context**
I'm not sure how to replicate this, but I have encountered a situation where two _identical_ cells (one was simply the content of the other copy/pasted in) result in one having its inline expressions being rendered, and the other one not at all (I see the raw code for the eval, in red). 

After making some small edits to the problematic cell, sometimes it randomly fixes itself, though none of my edits touched any of the code being evaluated...

I'm sorry I can't provide reproducible steps, it happened while working and I don't know how to reproduce it nor what fixed it... Posting in case you have any idea of what could be going on.

### Reproduce the bug

I wish I knew :)

**Comment by fperez** [comment]
Ok, here's an example, that's even weirder - the cell is rendering _partially_ - some expressions evaluate fine, others like a simple `1+1` do not at all:

![image](https://user-images.githubusercontent.com/57394/224936817-26719fd6-f04a-490c-9deb-e548ca5bac7f.png)

I'm pretty clueless as to what's going on...

**Comment by fperez** [comment]
In the example above, I duplicated the cell so could show both the source and the rendered content.

**Comment by agoose77** [comment]
Do you get any errors in the JS console?

**Comment by fperez** [comment]
Ah, unfortunately it was late and I was very tired, and I didn't think of capturing them, sorry! I'll keep an eye out and will grab them, if any, next time I encounter the issue.

**Comment by fperez** [comment]
BTW, this isn't the case in the above, since even `1+1` wasn't rendering, but I just had what I thought was a similar case, but then I realized it was the fact that Python exception errors weren't being communicated at all. See a small illustration here (not my original case):

![image](https://user-images.githubusercontent.com/57394/225103181-4de333c1-4830-4519-a2ba-f0f87706fb20.png)

This is all I'm seeing in the JS console, but it appeared a bit after entering the cell. I'm not sure if relevant or not:

![image](https://user-images.githubusercontent.com/57394/225103575-b3fb93c9-5a6c-4703-adfa-1a23c5dc1b36.png)

Thanks for any input, happy to test further if I can be useful!

**Comment by rowanc1** [comment]
I think that we never have rendered the error, but this *does* work with widgets, which already are using Jupyter infrastructure.

I think that we can do this pretty easily, will put together a PR:

![image](https://user-images.githubusercontent.com/913249/225165080-3c0c1e9b-68af-4179-80cf-66c7c359e5d7.png)

Trying to keep styles consistent with other error messages.

**Comment by rowanc1** [comment]
I think that #108 fixes this!

**Comment by fperez** [comment]
That's a _huge_ improvement, thanks so much @rowanc1!!

**Comment by agoose77** [comment]
I'm going to close this as it _seems_ like we've solved the issue. If there's actually more to this, then we can just reopen? :)
