### ISSUE TITLE
Cannot install via pip

### ISSUE THREAD

**Issue by MoritzImendoerffer** [executablebooks/jupyterlab-myst#12]
Hi, I am getting following error in Ubuntu 20.04 with conda:

>Could not find a version that satisfies the requirement jupyterlab-myst
>ERROR: No matching distribution found for jupyterlab-myst

any ideas how I can find out which dependencies were not met?

**Comment by pohlt** [comment]
It seems that jupyterlab-myst has not yet been uploaded to PyPI: https://pypi.org/search/?q=jupyterlab-myst
If you want to install it, you have to download its sources, I guess.

**Comment by agoose77** [comment]
I'm closing this now that we have a release on PyPI!
