### ISSUE TITLE
Citations do not show up in the Jupyter lab interface

### ISSUE THREAD

**Issue by arinbasu** [executablebooks/jupyterlab-myst#127]
Hi All,
I was working on a paper in Jupyterlab using jupyterlab-myst (OS: MacOS Big Sur 11.7.4) on Firefox browser. I typed  
` {cite:p}`doi:https://doi.org/10.18637/jss.v040.i01`  ` in a markdown cell. 

Doing shift+return would not render the citation in the jupyter lab interface, but it rendered correctly in the rendered webpage. It also rendered correctly in the exported Word document as (Wickham, 2011) for reference.
This is a minor issue but if you can kindly fix this or explain this, that'd be excellent. 
Best,
Arindam Basu

**Comment by agoose77** [comment]
Hi @arinbasu, 

Citations and references are on our todo list, but currently not implemented for `jupyterlab-myst`. See [this issue](https://github.com/executablebooks/jupyterlab-myst/issues/70) for more information! :)

**Comment by rowanc1** [comment]
🔜🚀

Glad to see you over here, @arinbasu, this is very high on the priority list!! It requires extracting some tools from the `myst-cli` and bringing them over to be used by juptyerlab-myst!

**Comment by arinbasu** [comment]
Thank you Rowan and Angus. 
I believe this issue can be closed now.

**Comment by rowanc1** [comment]
Can we keep this one open and I will close the other one -- this issue is more focused on citations, and you will be notified when we complete this work!

**Comment by wragge** [comment]
Glad to hear this is being worked on -- just building my first Jupyter Book, so thanks! 

I understand that citations are not rendering yet, but I'm finding that if a Markdown cell contains a a citation, like ``{cite:p}`aReference` ``, the whole cell collapses and becomes invisible when I hit shift+enter. 

If  I click around where the cell is supposed to be I can open it again for editing, and the citations render fine when I build the Jupyter book. They just disappear in Lab.

I've got jupyterlab==3.6.3 and jupyterlab-myst==1.2.0.

It's easy enough to work around, but it does seem very odd.

**Comment by rowanc1** [comment]
@wragge I have a fix for that incoming, thank you for letting us know! There was a bug in some of the new hover-citations that is working differently in JupyterLab and caused a full crash!

**Comment by rowanc1** [comment]
Some progress on this in #161, still need to implement DOIs, but getting closer!

**Comment by juntyr** [comment]
Has there been any progress on implementing citation support?
