### ISSUE TITLE
Use markdown-it-docutils instead of markdown-it-myst

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/jupyterlab-myst#14]
### Describe the problem/need and solution

This package currently uses [markdown-it-myst](https://github.com/executablebooks/markdown-it-myst) for myst parsing and rendering in JupyterLab.

However, more recent development for the "MyST in Javascript" story has been happening over in [markdown-it-docutils](https://github.com/executablebooks/markdown-it-docutils). This implements the logic for roles/behaviors with MyST.

We should try re-using that package here, since it will likely see the majority of development in the future (markdown-it-myst might even be ready to deprecate, I am not sure?)

### Guide for implementation

For some other re-uses of markdown-it-docutils, check out [executablebooks/myst-vs-code@master/src/extension.ts](https://github.com/executablebooks/myst-vs-code/blob/master/src/extension.ts), to create https://marketplace.visualstudio.com/items?itemName=ExecutableBookProject.myst-highlight.

**Comment by chrisjsewell** [comment]
Yep 👍 my thinking was if markdown-it-myst my still be useful to "centralise" things, and minimise any code duplication between jupyterlab-myst and myst-vs-code (or indeed any other JavaScript implementation)?

**Comment by chrisjsewell** [comment]
It would be great if jupyterlab-myst could also have the configuration for the syntax exetensions, like myst-vs-code has.

**Comment by agoose77** [comment]
> It would be great if jupyterlab-myst could also have the configuration for the syntax exetensions, like myst-vs-code has.

Could you elaborate on this? :)
