### ISSUE TITLE
Feedback on v1.2.0: Math, Unknown Directives

### ISSUE THREAD

**Issue by mmcky** [executablebooks/jupyterlab-myst#143]
First up -- thanks for all the work done on this extension. This is a `game changer` for us and we are making use of `jupyterlab-myst` every day in our current workflows. 

## Description

Just compiling some feedback on `v1.2.0`. 

### Math

I am not sure how to pass in `latex` metadata such as 

```
"PP" : "\\mathbb{P}"
"RR" : "\\mathbb{R}"
```

as mathjax macros for use in the `jupyterlab-myst` context

<img width="628" alt="Screenshot 2023-05-17 at 12 18 49 pm" src="https://github.com/executablebooks/jupyterlab-myst/assets/8263752/96fc160c-0d4e-4afe-9db5-5da110079a52">

but I **really like** the error feedback it provides. 

### Unknown Directives (Break Rendering)

Currently unknown directives break the rendering

<img width="1324" alt="Screenshot 2023-05-17 at 12 23 52 pm" src="https://github.com/executablebooks/jupyterlab-myst/assets/8263752/4e4b01a2-18bf-4839-83d0-6bac8e2136ca">

which is sourced from:

````
## Exercises

```{exercise}
:label: markov-prop-1

Consider the binary (Bernoulli) distribution where outcomes $0$ and $1$ each have
probability $0.5$.

Construct two different random variables with this distribution.
```


```{exercise}
:label: markov-prop-2

Show by direct calculation that the Poisson matrices $(P_t)$ defined in 
{eq}`poissemi` satisfy the semigroup property {eq}`chapkol_ct2`.

Hints

* Recall that $P_t(j, k) = 0$ whenever $j > k$.
* Consider using the [binomial formula](https://en.wikipedia.org/wiki/Binomial_theorem).
```


```{exercise}
:label: markov-prop-3

Consider the distribution over $S^{n+1}$ previously shown in {eq}`mathjointd`, which is

$$
    \mathbf P_\psi^n(x_0, x_1, \ldots, x_n)
        = \psi(x_0)
        P(x_0, x_1)
        \times \cdots \times
        P(x_{n-1}, x_n)
$$ 

Show that, for any Markov chain $(X_t)$ satisfying {eq}`markovpropd`
and $X_0 \sim \psi$, the restriction $(X_0, \ldots, X_n)$ has joint
distribution $\mathbf P_\psi^n$.
```


```{exercise}
:label: markov-prop-4

Try to produce your own version of the figure {ref}`flow_fig`

The initial condition is ``ψ_0 = binom.pmf(states, n, 0.25)`` where ``n = b + 1``.
```
````

https://github.com/QuantEcon/continuous_time_mcs/blob/master/lectures/markov_prop.md

This is reasonable behaviour so perhaps the solution is to build support for [sphinx-exercise](https://github.com/executablebooks/sphinx-exercise) style directives

## Proposed solution

**math:**

- [ ] identify a way to set `tex` macros for math rendering and document in `docs`

**Comment by rowanc1** [comment]
Hi @mmcky -- you can add math-macros through the frontmatter, and they work well! See the docs for that here:
https://myst-tools.org/docs/mystjs/math#math-macros

Although, I am not sure if that will survive the jupytext conversion, so that might need some more work to iron out.

I have added support for sphinx-exercise in https://github.com/executablebooks/mystjs/pull/399, excited to bring it over here in the next few days!

**Comment by rowanc1** [comment]
Putting together a few improvements to show better errors around unknown directives @mmcky:

![image](https://github.com/executablebooks/myst-theme/assets/913249/21d35982-a211-4535-85c9-4a08edb924ab)

- https://github.com/executablebooks/myst-theme/pull/108
- https://github.com/executablebooks/mystjs/pull/403

I think there are some other improvements that we can do, like optimistically rendering the children, but this is a good first step!

I will get that in the theme, and hopefully we can cut another minor release with the markdown renderer and the exercise updates.

**Comment by rowanc1** [comment]
@mmcky -- going to close this issue as I think that we have addressed all the immediate feedback you listed here. We will get another release out soon for you to get more feedback on!
