### ISSUE TITLE
Support JupyterLab 4.0

### ISSUE THREAD

**Issue by iloveopen** [executablebooks/jupyterlab-myst#148]
I have installed jupyterlab 4.0 and jupyterlab_myst 1.2 with pip. 
But it didn't work well. 
See the picture.
![image](https://github.com/executablebooks/jupyterlab-myst/assets/11310635/748c16ae-5efd-4231-bdc7-46950e4ea83e)

Is it a bug or something I need to conf?

**Comment by rowanc1** [comment]
Thanks for the report! We are currently working on jupyterlab 4 support, but aren't quite there yet. @agoose77's branch is here: 
- #142

**Comment by dcherian** [comment]
Can this be closed by https://github.com/executablebooks/jupyterlab-myst/pull/155

**Comment by rowanc1** [comment]
We have just released support for JupyterLab 4.0 in `v2.0.0`! Looking forward to your feedback.

**Comment by rowanc1** [comment]
@dcherian yes! :) Missed your comment before I posted mine! Thank you.
