### ISSUE TITLE
Labels are not allowed to be set in a PR if not on EB team

### ISSUE THREAD

**Issue by GlobalMin** [executablebooks/jupyterlab-myst#154]
I created PR #153 and noticed one check insta failed due to it not having a label. That's a reasonable check and policy, BUT I can't add a label so new PR's will always fail this check until someone on the EB team adds one. That seems counter productive to me and might hide some otherwise good edits with a ❌ that is simply due to this detail. 

Can the team consider changing this permission and explain the reasoning if not?

**Comment by rowanc1** [comment]
I did take a look, but I am not sure how to allow this via github. We are using some default CI tools from the jupyter ecosystem, so I think this is going to be hard to fix. Of all our repos, this is the only one that is enforcing PR labels.

I am going to close this, but we will certainly look at your/any PRs regardless of if they are failing. The label can be added, and it goes green independently from the other tests, so it usually isn't too bad!
