### ISSUE TITLE
jupyterlab-myst extension causes issues problems with viewing the notebook in the browser

### ISSUE THREAD

**Issue by MatusGasparik** [executablebooks/jupyterlab-myst#166]
## Description
I worked on a notebook yersterday and today I noticed that large chunks of it (basically everything except for the top cell with some imports) was misteriously missing. But the notebook file is big, `cat`-ing it relealed that the content is there, it just want show in the browser for some reason.

 I checked the browser console and saw something related to this extension:

<img width="1083" alt="image" src="https://github.com/executablebooks/jupyterlab-myst/assets/15058994/b4c2191a-f6b2-4b04-8a23-887d3cfab924">

So I tried deactivating the extension in the left-panel and refreshing and voilà - the notebook contenst magically appeared:

![Bildschirmaufnahme 2023-06-30 um 09 52 53](https://github.com/executablebooks/jupyterlab-myst/assets/15058994/d2e8d897-372e-4aee-86be-65c1edd9111c)

## Additional notes
**Versions**
- _jupyterlab-myst_: 1.2.0
- _jupyterlab_: 4.0.0
- _chrome_: 114.0.5735.198
- OS: macOS 12.6.2 (Apple M1 Max)

**Comment by agoose77** [comment]
Can you share the notebook that causes this?

**Comment by rowanc1** [comment]
Thanks @MatusGasparik for the bug report. @agoose77 it could potentially be this line:
https://github.com/executablebooks/jupyterlab-myst/blob/dedbb1d785a02612da05fa798c7091c25b607a59/src/metadata.ts#L13

Do you know by chance when `getMetadata` was introduced, perhaps later than JupyterLab 4.0.0?

**Comment by rowanc1** [comment]
Actually, @MatusGasparik please upgrade to `v2.0.0` of the `jupyterlab-myst` library, the previous one was not compatible with JupyterLab 4.0!

**Comment by agoose77** [comment]
@rowanc1 good eyes. I misread the version as 2.0, this makes much more sense.
