### ISSUE TITLE
code-blocks always have black text

### ISSUE THREAD

**Issue by jans-code** [executablebooks/jupyterlab-myst#167]
No matter what theme i choose and no matter how i define the code-blocks in markdown, they are always rendered with black text.

This is also true when defining a language, for which syntax highlighting works in the default jupyter markdown view.

But with jupyterlab_myst I always get black text, i was able to fix the css in my dark theme, so the code was at least readable.

**Comment by rowanc1** [comment]
Thanks for the bug report @jans-code. @agoose77 most of the dark-mode is triggered off of CSS, except for the code, which does need to load a new style using JS.

Where we define the styles to look to Jupyter:
https://github.com/executablebooks/jupyterlab-myst/blob/dedbb1d785a02612da05fa798c7091c25b607a59/tailwind.config.js#L4

The place where we need to also look to that style and change it:
https://github.com/executablebooks/jupyterlab-myst/blob/dedbb1d785a02612da05fa798c7091c25b607a59/src/widget.tsx#L153

Something like looking for the theme on the body should work:
```js
document.body.dataset.jpThemeLight === 'false'
```

I will put together a PR.

**Comment by rowanc1** [comment]
Nice, that works well! It does require a page refresh or to re-execute the cell but I think that is ok for now.

![image](https://github.com/executablebooks/jupyterlab-myst/assets/913249/bbe84238-99f2-4a1b-8020-cc573bb6416f)

**Comment by rowanc1** [comment]
This has been fixed and merged, we will get a patch release out soon!

**Comment by agoose77** [comment]
> The place where we need to also look to that style and change it:

Oops. Been staring at that code so much of late that I forgot to actually read it!

**Comment by rowanc1** [comment]
This is released in [v2.0.1](https://github.com/executablebooks/jupyterlab-myst/releases/tag/v2.0.1)!
