### ISSUE TITLE
Possible fix for current main branch's failed test BUT please explain how to properly install env from scratch

### ISSUE THREAD

**Issue by GlobalMin** [executablebooks/jupyterlab-myst#169]
Hi EB team and @agoose77,

I like using real issues to practice digging into new topics, so the effort can do something real potentially. I think I've found a potential fix for the linting error in the current main branch, so I'll start with that.

In the `eslintrc.js` file there is a section for exclusions to lint rules and this is the one I was getting from my local version, and after the line below, the lint check passed. 

``` shell
module.exports = {
  ...
  rules: {
    ...
    '@typescript-eslint/no-non-null-assertion': 'off'
  },
  ...
}
```

Unfortunately this didn't work when I forked the current main and pushed this change. I have to sort of pause this investigation though because while I've been working with this repo today, I have found it so challenging to install in a reliable workflow to the point I can't seem to get the same results two times in a row at all.

The repo hosts a ton of javascript and typescript, so I know that this is just how it goes to a large degree. I also am not sure if I'm simply just not aware of some standard series of steps that would avoid all the unpredictable patterns I have been stuck in with the order in which I try installing the editable environment from pyproject.toml, how I handle node_modules, and finally which `jlpm` commands I use.

I'm happy to give a ton of details if someone reads this and replies but for now I want to simply ask the dev team or whoever feels comfortable that their install flow works across software/hardware/cloud/Docker -

How would you successfully build this repo and labextension from a GitHub Codespace? There are multiple ways to go about the base image, conda versus CPython, installing node, using npm or yarn, and probably more I'm forgetting. I have read all the docs and realize the README.md covers this but it's too vague for me, so I hope that either I can learn what I'm doing to make this hard or if it is truly a delicate process for all then I would suggest adding a Dockerfile to the repo that can help everyone start the same way.

**Comment by rowanc1** [comment]
Just saw that there is a warning on the non-null assertions in #170 which is what you were referring to! I think that we should probably improve the code around there to explicitly raise an error if that widget isn't defined when we attach it.

**Comment by GlobalMin** [comment]
> I think that the linting fails because of the `package.json` which is created in the release process having 4 spaces instead of 2. This is something we need to probably improve in upstream release manager to look at or run prettier before committing this code as part of the release!
> 
> For installing, you should use the `jlpm` that comes with jupyterlab 4.0. I think that is yarn 3. When you do that it should use the yarn.lock and create a reproducible build!

@rowanc1 This seems to work. I will test on a few machines and post back if I can show the behavior I found earlier, but this sequence seems to work more or less for me locally.

```
python3.10 -m virtualenv venv
pip install jupyterlab
jlpm
jlpm build
```
