### ISSUE TITLE
Publish via conda-forge

### ISSUE THREAD

**Issue by rgaiacs** [executablebooks/jupyterlab-myst#171]
Duplicated of https://github.com/executablebooks/jupyterlab-myst/issues/71 because it is closed.

I can't find this package in [conda-forge](https://github.com/orgs/conda-forge/repositories?q=myst&type=all&language=&sort=)

![Screenshot 2023-07-11 at 17-00-09 conda-forge](https://github.com/executablebooks/jupyterlab-myst/assets/1506457/63cac0d2-224d-4937-930e-09f65434b38f)

**Comment by quctex** [comment]
I did not try to install, but is it here? https://anaconda.org/conda-forge/jupyterlab-myst

**Comment by agoose77** [comment]
We already have a package being published in conda-forge: https://prefix.dev/channels/conda-forge/packages/jupyterlab-myst

:)

**Comment by rgaiacs** [comment]
Thanks for the links. Now GitHub search list it to me.

![Screenshot 2023-07-17 at 08-30-41 conda-forge](https://github.com/executablebooks/jupyterlab-myst/assets/1506457/5ac7515a-1fb1-4954-a18f-bf3f537a62be)
