### ISSUE TITLE
Incompatibility with jupyterlab_rise

### ISSUE THREAD

**Issue by nthiery** [executablebooks/jupyterlab-myst#181]
Not sure if this is a jupyterlab-myst or jupyterlab-rise issue, so posting [there](https://github.com/jupyterlab-contrib/rise/issues/46) with this crosspost here.

**Comment by nthiery** [comment]
Tough choice indeed between the two. I had tried jupyterlab-deck a couple months ago (but not with myst), and jupyterlab-rise looked closer -- from the user perspective -- to the original rise extension, in particular in term of navigation and shortcuts. Which is why I went for jupyterlab-rise for now. Will try now how jupyterlab-deck and myst interact.

**Comment by nthiery** [comment]
I confirm that myst cells render seem to render properly with jupyterlab-deck.

**Comment by agoose77** [comment]
Fab! I'll close this for now -- RISE is not super supported these days, and deck is much more extension friendly.
