### ISSUE TITLE
jupyterlab-myst breaks navigating from the TOC outline

### ISSUE THREAD

**Issue by parmentelat** [executablebooks/jupyterlab-myst#184]
## Description

the outline TOC is no longer usable to navigate across the notebook once `jupyterlab-myst` is installed

to reproduce:

- install a fresh jupyterlab environment
  - open a notebook whose height is a few viewports
  - make sure that one of the headers ends up below the bottom of the viewport
  - in the jlab outline, click that header, the corresponding cell gets selected and the notebook scrolls so this cell becomes visible
- on top of that, install `jupyterlab-myst`
  - restart jlab and reproduce the same
  - the header cell gets selected, but the notebook does not scroll

## Proposed solution

I have not yet been able to investigate this issue, but am willing to, with a little guidance :)

## Additional notes

initially posted in https://github.com/jupyterlab/jupyterlab/issues/14897 
before I could pinpoint this to `jupyterlab-myst`

**Comment by parmentelat** [comment]
duplicated from the original issue, hopefully makes things clearer

![navigation-toc-broken](https://github.com/jupyterlab/jupyterlab/assets/4519227/4e76ce78-4092-4f1a-b5ff-92952b8e4f4d)

**Comment by rowanc1** [comment]
It looks like this has changed in JupyterLab 4 and this is no longer a simple anchor link as the notebook has become virtualized.

I think we need to add a new factory or something similar to this:

https://github.com/jupyterlab/jupyterlab/blob/1d989bad87e89307a336d2f671c9cc98ec37f5e9/packages/markdownviewer/src/toc.ts#L90

**Comment by parmentelat** [comment]
a little surprisingly, I have just noticed that the feature starts working again, apparently if I create an artificial delay in the notebook loading phase

more specifically:

- I add a breakpoint, for example in the `activate` part of the myst plugin (but it does not seem to matter, just pick something that is called once at load-time)
- then, upon reloading a notebook that otherwise exhibits the faulty behaviour, I immediately click on the 'proceed' button of the debugger, 
- and bingo, the TOC works again..

in my limited understanding of the system, this could suggest some asynchronous function that is not properly awaited, or some similar flaw that would occur at load time

I'm still puzzled that the issue clearly relates to jupyterlab-myst though, since without this extension everything works fine...

**Comment by parmentelat** [comment]
finally I'd like to report that the issue happens also in the "Markdown Preview" and the "Editor" document views, and in both cases apparently adding an artificial delay as explained above makes the feature working again

**Comment by parmentelat** [comment]
looks like this might very well be an issue on jupyterlab proper, and that it is being addressed here

https://github.com/jupyterlab/jupyterlab/pull/14884

**Comment by parmentelat** [comment]
to be more explicit, the referenced PR does fix the issue that I have when using the TOC with the jupyterlab-myst extension loaded
clearly a workaround because there obviously are deeper issues in the jlab loading phase that create the conditions for the issue
currently this is a major productivity impediment, so if the PR makes it to being merged, whether it's a clean fix or not, 
would be a great relief already...

**Comment by parmentelat** [comment]
quite obviously, as per both
https://github.com/jupyterlab/jupyterlab/issues/14897
and
https://github.com/jupyterlab/jupyterlab/issues/14591
the issue is totally a jupyterlab one after all

am closing this one

**Comment by rowanc1** [comment]
Thanks for following up @parmentelat!
