### ISSUE TITLE
missing support for ```{div} directive

### ISSUE THREAD

**Issue by parmentelat** [executablebooks/jupyterlab-myst#200]
using a {div} directive like so in a jupyterlab notebook
<img width="224" alt="image" src="https://github.com/executablebooks/jupyterlab-myst/assets/4519227/ccfffea1-5a9b-456e-ae20-f50d5c76f9d1">

 results in an output like this
<img width="276" alt="image" src="https://github.com/executablebooks/jupyterlab-myst/assets/4519227/958e2771-ce6e-4ba4-bc34-042ef5cb6a05">

## Description
as far as I understand this is a chunk of legal MyST; at least the same code processed through jupyter-book results in a readable HTML output

## Proposed solution

my understanding, from this comment below, is that not much is needed to make this widely available, am I correct ?
https://github.com/executablebooks/jupyter-book/issues/1928#issuecomment-1824773862

## Additional notes

if so a public release of this feature would be much appreciated :)

**Comment by rowanc1** [comment]
Thanks @parmentelat, underlying tracking issue is here:
https://github.com/executablebooks/mystmd/issues/749

We have thus far implemented in AST, not yet the directive. Happy to take a PR or pointers to the docs/test cases on what the options to the directives should be!

**Comment by agoose77** [comment]
I'm closing this as it's an upstream feature request! :)

**Comment by rowanc1** [comment]
Added in:
- https://github.com/executablebooks/mystmd/pull/1140

**Comment by rowanc1** [comment]
This is released in jupyterlab-myst `2.4.0`!
