### ISSUE TITLE
Cannot edit rendered exercise solution dropdown cell

### ISSUE THREAD

**Issue by psychemedia** [executablebooks/jupyterlab-myst#213]
Using the exercise solution example from the MyST documentation with a `:class: dropdown` setting, once the markdown is rendered (in JL4.1 at least), there seems to be no way of getting the cell back into the edit mode, not even by defining a custom 'edit mode' keyboard shortcut.

<img width="1038" alt="image" src="https://github.com/executablebooks/jupyterlab-myst/assets/82988/c3a7c281-e8e5-4db5-93f2-1c90499ed44b">

**Comment by psychemedia** [comment]
Hmm.. this seems to be intermittent. And I can't reliably replicate it.

**Comment by agoose77** [comment]
@psychemedia how often do you feel that this happens?

**Comment by psychemedia** [comment]
After trying to replicate it, very infrequently... will close this for now unless I can track down what the actual issue is...
