### ISSUE TITLE
Jupyterlab-myst don't highlight URL when enabled

### ISSUE THREAD

**Issue by Hoxbro** [executablebooks/jupyterlab-myst#219]
## Description

I sometimes paste URLs into a markdown cell and have noticed I can't click on them when I have jupyterlab-myst enabled.

### Jupyterlab-myst enabled
![ Screenshot 2024-02-22 13 35 00](https://github.com/executablebooks/jupyterlab-myst/assets/19758978/1909236e-4e39-4c49-bb57-23f39b3d6ee5)

### Jupyterlab-myst disabled
![ Screenshot 2024-02-22 13 35 30](https://github.com/executablebooks/jupyterlab-myst/assets/19758978/51adb7e7-0817-4b6d-933c-2f8ff38d025d)

**Comment by rowanc1** [comment]
Thanks @Hoxbro.

@agoose77 we turned the "linkify" plugin on a while ago in the base mystmd packages (https://github.com/executablebooks/mystmd/pull/53), are you seeing this in your dev environment?

**Comment by agoose77** [comment]
I can confirm this appears to be a regression!
