### ISSUE TITLE
Item lists rendered as task list

### ISSUE THREAD

**Issue by nthiery** [executablebooks/jupyterlab-myst#220]
I just noticed that, with jupyterlab-myst 2.3.1, itemized list are (systematically?) rendered as task list.

## How to reproduce

- Start jupyterlab with myst >= 2.3.0 installed

  E.g.: click the [binder button](https://mybinder.org/v2/gh/executablebooks/jupyterlab-myst-quickstart/main?urlpath=lab) from the documentation. Be patient until it starts. In a terminal, run `pip install jupyterlab-myst==2.3.1`. Reload page.

   Do we have a jupyterlite under hand with the latest jupyterlab-myst available for this kind of quick tests?

- Create a new cell with the following content

    ```
    - foo
    - bar
    ```

- Render the cell.

### Expected

An itemized list

### Got

A task list

## Note

- Reverting to 2.3.0 has no effect. Reverting to 2.1.0 fixes that issue
- This does not happen in the sandbox on mystmd.org.

**Comment by jeremy886** [comment]
I also had the same problem and needed to downgrade to 2.1.0 to fix this.

**Comment by parmentelat** [comment]
same here - thanks for pointing out the working version !

in my case I also have upgraded to jlab 4.1.x; I'm pointing it out because I have seen a few extensions break with 4.1.x, so that's an angle that might be worth exploring too.

**Comment by agoose77** [comment]
Thanks all! I'll look into this!

**Comment by tavin** [comment]
https://github.com/executablebooks/jupyterlab-myst/pull/223

**Comment by agoose77** [comment]
Closed by #223

**Comment by parmentelat** [comment]
this is a very visible issue with our students setups, it would help a lot if that fix could be made shortly part of the latest pypi version... thanks in any case !
