### ISSUE TITLE
Incorrect display of bullet and numbered lists after updating to  `jupyterlab-myst == 2.3.1`

### ISSUE THREAD

**Issue by godaygo** [executablebooks/jupyterlab-myst#224]
## Description
After updating to `jupyterlab-myst == 2.3.1` bullet and numbered lists are always displayed/shown as tasks lists.
## Additional notes
`jupyterlab-myst == 2.3.1`

**Comment by rowanc1** [comment]
@agoose77 i have merged and tried to release this today as 2.3.2.

Something in the jupyter-release action is broken. Can you take a look when you are back from vacation!

**Comment by agoose77** [comment]
Closed by the latest release(s)!
