### ISSUE TITLE
You only show examples with iPython kernel, can other kernels use this?

### ISSUE THREAD

**Issue by cjwomack** [executablebooks/jupyterlab-myst#225]
You only show examples with iPython kernel, is there support for other kernels?

Do other kernels need to modified to offer support for this?

Just was experimenting with this...

As a personal use case, I'm currently using jupyterlab-myst 1.2.0 as official matlab kernel hasn't migrated to Jupyter Lab 4 as well as matlab Metakernel [https://github.com/Calysto/matlab_kernel]( https://github.com/Calysto/matlab_kernel)

**Comment by rowanc1** [comment]
Any kernel that works with Jupyter will also work with JupyterLab MyST! They shouldn't need to add specific support as this extension only enhances the markdown side of Jupyter's native experience.

There may be some potential improvements to be made to suppor the [inline execution](https://mystmd.org/guide/quickstart-jupyter-lab-myst#inline-expressions) (`{eval}` roles), however, that is also basic functionality in the Jupyter protocol, so should hopefully work out of the box!

**Comment by cjwomack** [comment]
I didn't find it to work... Different time zone prevents me from elaborating at the moment.

**Comment by agoose77** [comment]
Please do elaborate here if you find time, it would be good to look into any issues here. I'm assuming that you're trying to use the expressions support in the Calysto kernel?

I looked at the MatLab extension. I *think* you can install the latest version with JupyterLab 4, it just means that the Lab plugin won't work properly.

It might be that the kernel doesn't implement expressions support, though; we can separately look into that.
