### ISSUE TITLE
admonition text-wrap failure in version 2.4.2

### ISSUE THREAD

**Issue by zillionare** [executablebooks/jupyterlab-myst#242]
## Description

tested in version 2.4.2, admonition failed to wrap extra-length lines:

![image](https://github.com/executablebooks/jupyterlab-myst/assets/7206696/47cccf36-5bea-479e-b06e-ff91e7e6c8b5)

this works in version 2.3.1, 2.3.2 (no test beyond version 2.3.2)

![image](https://github.com/executablebooks/jupyterlab-myst/assets/7206696/51d205ac-0e4d-445b-8b66-a62c16a04feb)

## Proposed solution

text in admonition should wrap up.

## Additional notes

seems admonition text was rendered as code.

**Comment by agoose77** [comment]
Hi, could you share the source for your bug report? It looks like your content is being embedded in the admonition as a code-block, so it's not being wrapped.

**Comment by zillionare** [comment]
the source:

```
``` {note}
    plotly 中的轴类型有 linear（默认）, log, date, category 和 multicategory。如果我们没有指定轴类型，plotly 会按以下顺序猜测轴类型：multicategory（只有数据本身是嵌套数组时）、date 或者 category（在我们最初的例子，会被优先判定为 date 型，从而终推断），如果还不能决定，将使用 linear。
```
```

**Comment by zillionare** [comment]
``` {note}
    plotly 中的轴类型有 linear（默认）, log, date, category 和 multicategory。如果我们没有指定轴类型，plotly 会按以下顺序猜测轴类型：multicategory（只有数据本身是嵌套数组时）、date 或者 category（在我们最初的例子，会被优先判定为 date 型，从而终推断），如果还不能决定，将使用 linear。

```

**Comment by zillionare** [comment]
[lesson17.ipynb.zip](https://github.com/executablebooks/jupyterlab-myst/files/15414734/lesson17.ipynb.zip)
in case you need the whole file

**Comment by agoose77** [comment]
Admonition contents must not be indented unless you wish for them to be parsed as code-blocks :), i.e.
````markdown
``` {note}
plotly 中的轴类型有 linear（默认）, log, date, category 和 multicategory。如果我们没有指定轴类型，plotly 会按以下顺序猜测轴类型：multicategory（只有数据本身是嵌套数组时）、date 或者 category（在我们最初的例子，会被优先判定为 date 型，从而终推断），如果还不能决定，将使用 linear。
```
````

P.s., you can nested fenced blocks like admonitions by ensuring the number of backticks increases from inside-to-out, e.g.

```````markdown
````note
This contains a figure!
```figure foo.png
```
````
```````
