### ISSUE TITLE
Use CI to test + release

### ISSUE THREAD

**Issue by agoose77** [executablebooks/jupyterlab-myst#27]
### Describe the problem/need and solution

Currently the release process is:
1. `jlpm publish` which allows us to bump the version, and publish to NPM
2. `pyproject build -ws` which builds the wheel + sdist
3. `twine upload dist/*`

This is a bit cumbersome, and I would like to be able to perform releases without building locally. We should add CI infrastructure for this

**Comment by blink1073** [comment]
I'd humbly suggest using [jupyter releaser](https://jupyter-releaser.readthedocs.io/en/latest/how_to_guides/convert_repo.html), which is a secure way to produce automated releases using your own credentials instead of shared credentials.

**Comment by rowanc1** [comment]
This was added by @agoose77 in:
- https://github.com/executablebooks/jupyterlab-myst/commit/3fc9fb6cf0d5133567b8fc5cc5e3cecfe92fb015

🚀
