### ISSUE TITLE
Markdown Headers Do Not Render

### ISSUE THREAD

**Issue by psychemedia** [executablebooks/jupyterlab-myst#29]
### Describe the bug

Headers in markdown cells appear not to render?

![image](https://user-images.githubusercontent.com/82988/151008505-1bd407f4-954c-4bfd-becd-a27bd1a8d9a6.png)

### Reproduce the bug

In Binder Demo, Markdown cell with content:

```
## Header

Content
```

The header is not rendered correctly.

### List your environment

jupyterlab-markup==1.0.1
-e git+https://github.com/executablebooks/jupyterlab-myst@f44fe71d54375cb7d5b558f0fca337d7881f72bd#egg=jupyterlab_myst

**Comment by psychemedia** [comment]
@agoose77 Does that require restarting the server? (I'm running in MyBinder atm...).

**Comment by chrisjsewell** [comment]
This works fine for me locally FYI

**Comment by agoose77** [comment]
I can't reproduce this either. Can you check again on Binder?

**Comment by psychemedia** [comment]
Seems to work on Binder now.
