### ISSUE TITLE
Supporting other sphinx-extension types in JupyterLab

### ISSUE THREAD

**Issue by psychemedia** [executablebooks/jupyterlab-myst#31]
### Describe the problem/need and solution

As I understand it, Jupyter Book is a custom sphinx build closely related to MyST and `jupyterlab-myst` supports rendering of "core" MyST directives.

Many users may be working in a further extended Sphinx environment configured with extensions such as `sphinx-exercise`. If authors want similar views in the Jupyter Book and JupyterLab/RetroLab environments, they will presumably need to install a JupyterLab styling extension (if available) to complement any Sphinx extensions they rely on in Jupyter Book renderings.

Is there anything to be learned from developing this extension that can be used to provide guidance for how create JupyterLab styling extensions to match Sphinx styling extensions? Is it possible to write code once that works in both?

**Comment by chrisjsewell** [comment]
Hey Tony 👋 there is currently a fair bit of work going on around the JS side of MyST (not just for JupyterLab but also VS Code, Curvenote, ...), and even more generally MyST as a language agnostic specification 

The internals of jupyterlab-myst will probably change quite a lot as we progress, so I would be a bit tentative about proposing a best way to do this right now

See e.g. https://executablebooks.github.io/mystjs

**Comment by psychemedia** [comment]
Ok - thanks.

I also just noted this minimal example for adding a custom admonition to the Jupyter Book Sphinx engine: https://github.com/executablebooks/meta/discussions/655

It would be really handy if a similar example was possible for adding things to `jupyterlab-myst` or whatever it morphs into.

**Comment by chrisjsewell** [comment]
Creating a sphinx extension is purely tied to sphinx/python usage, there is no read across to `jupyterlab-myst` (written in JS), or any other ecosystem
But this is where we are trying to look at language agnostic ASTs etc
