### ISSUE TITLE
Poor Perfromance in Rendering Markdown Cells

### ISSUE THREAD

**Issue by psychemedia** [executablebooks/jupyterlab-myst#33]
### Describe the bug

Hi

I appreciate this is still an experimental extension, but I thought it worth noting that I have noticed poor rendering times of markdown cells with the extension installed. Code cells render immediately, but I am experiencing up to 2s of delay in all markdown cells rendering (they all seem to render at the same time?)

Chrome Version 99.0.4844.84 (Official Build) (x86_64) / MacOS.

### Reproduce the bug

- install extension;
- load notebook.

Markdown cells often (but not always?) tardy in rendering, whether or not they include MyST additions.

**Comment by agoose77** [comment]
Do you have any example notebooks that we could use to reproduce this?

**Comment by psychemedia** [comment]
Every notebook I open, irrespective of length / number of cells. It may be a side effect of the (Chrome) browser having lots of open tags / memory issues, (JupyterLab is very slow to load) but the markdown cells rendering late issue is a feature only when the the `jupyterlab-myst` extension is installed.

**Comment by agoose77** [comment]
@psychemedia this sounds like it might be a JupyterLab feature that optimises the loading of large notebooks. Could you upload a screen recording to demonstrate what is happening? And confirm that you're not using `jupyerlab-imarkdown`?

**Comment by psychemedia** [comment]
It happens with small notebooks; things are fine if I uninstall `jupyterlab-myst`. If I uninstall `jupyterlab-myst`and then reinstall it, I get the delay on rendering the markdown cells the first time I open a notebook (I think... This seems repeatable for me atm, but I hadn't noticed that feature before.) I think I may have `jupyerlab-imarkdown` installed.

FWIW, it might be useful to have an extension setting that allows the user to enable/disable the `jupyter-myst` features, if that's possible.

**Comment by agoose77** [comment]
There is a flag that turns off the MyST features altogether - we don't have a finer granularity than that (as a deliberate decision, as it's my understanding that we want to deliver "MyST" as a single experience).

**Comment by psychemedia** [comment]
I think the issue is a Chrome one: with lots of open tabs in Chrome, opening a new JupyterLab instance can be slow, and rendering markdown cells in a newly opened notebook can be very slow.

**Comment by agoose77** [comment]
Thanks for the update :)
