### ISSUE TITLE
jupyterlab-myst does not seem to handle the math directive properly

### ISSUE THREAD

**Issue by jmshea** [executablebooks/jupyterlab-myst#34]
### Describe the bug

**context**
I am writing a book using JupyterBook and trying to add a labeled equation. I am using jupyterlab-myst to help display the effects of MyST directives. I encountered problems when I  added math content using the {math} directive

*Input MyST Markdown:*
<img width="469" alt="image" src="https://user-images.githubusercontent.com/6517343/165790666-4a4f5302-fc8b-40af-a9c8-08bafcfee887.png">

**expectation**
I expected the math content to be displayed using MathJax. Acceptable fallbacks would be just showing the myst code or showing the formatted myst directive box with the math not rendered.

**bug**
But instead the math is completely hidden on rendering if no label. If I add a label, jupyterlab-myst gives "Error: Content block expected, but none found." 

*Rendered version:* 
<img width="469" alt="image" src="https://user-images.githubusercontent.com/6517343/165790705-ad0fc2ff-080c-4ff7-b6f3-03df835161ee.png">

**problem**
This is a problem for people who use the {math} directive because they will not even be able to see where their math content is!

### Reproduce the bug

Add math in a {math} directive to a JupyterLab notebook with jupyterlab-myst installed. Render to see the problems.

A minimal example is here: https://github.com/jmshea/Foundations-of-Data-Science-with-Python/blob/main/08-random-variables/jm-math-problems.ipynb

### List your environment

> jupyter-book --version
Jupyter Book      : 0.12.3
External ToC      : 0.2.3
MyST-Parser       : 0.15.2
MyST-NB           : 0.13.2
Sphinx Book Theme : 0.1.10
Jupyter-Cache     : 0.4.3
NbClient          : 0.5.13

> pip list |grep jupyterlab-myst
jupyterlab-myst                   0.1.6

**Comment by agoose77** [comment]
This is *sort of* a bug - right now `jupyterlab-myst` release doesn't implement the math directive. However, even when I update to the latest `markdown-it-docutils` version, the math doesn't render at all, which I'm looking into.

**Comment by agoose77** [comment]
@jmshea could you try 0.1.7a0 and see whether it fixes things?

**Comment by jmshea** [comment]
@agoose77 I would be happy to do that, but I am not sure where I can find 0.1.7a0. I don't see it on PyPi, nor as a release or tag here. Should I just install from the current repo head?

**Comment by jmshea** [comment]
@agoose77 Thank you. This is much better in 0.1.7a0! The equations display properly in both cases. I will close this, but I will add a separate request for a feature enhancement to display the equation label if it has one.

Thanks again.
