### ISSUE TITLE
PyPI: make alpha release?

### ISSUE THREAD

**Issue by agoose77** [executablebooks/jupyterlab-myst#4]
This issue is to track the release of this package on NPM and PyPI. We should release an alpha at some point. Currently the PyPI package for `jupyter-book` sits under @choldgraf, but I'm also happy to release it under my account if it helps share the maintenance burden.

**Comment by choldgraf** [comment]
+1 from me on making a release.

Do you know if there's a way to have a generic "organizational account" on PyPI? Or does it have to be attached to a specific person?

If the latter, I'm happy to just create one and add you all as admins on it. I think it's probably easier to keep track of "admin ownership status" if there are fewer unique owners across the EBP packages.

**Comment by agoose77** [comment]
From what I can see, organisational accounts are a planned but as-yet unrealised feature of PyPI. So I think your proposal is the best way forward here!

**Comment by chrisjsewell** [comment]
> Do you know if there's a way to have a generic "organizational account" on PyPI? Or does it have to be attached to a specific person?

this is why we have @ebp-bot, https://pypi.org/user/ebp-bot/

**Comment by agoose77** [comment]
> this is why we have @ebp-bot, https://pypi.org/user/ebp-bot/

So, is this user just used for releasing via CI?

**Comment by chrisjsewell** [comment]
Just as a central account for adding PyPI maintenance etc, then you just generate an API Keys for releases as done in our other packages, e.g. https://github.com/executablebooks/sphinx-external-toc/blob/5f0cbdc568580875d5909a3de967c1963b7f858e/.github/workflows/tests.yml#L61

**Comment by choldgraf** [comment]
I opened up an issue to document the ebp-bot here, let me know if I missed something: https://github.com/executablebooks/meta/issues/411

**Comment by Pugio** [comment]
Hi, what's the current status of releasing this? I would really love advanced Markdown support in my lab notebooks.
Is there anything I can do to help move this along? I'm happy to help...

**Comment by agoose77** [comment]
@chrisjsewell @choldgraf I'm now strongly considering using `jupyter book` for my PhD thesis, so I could afford to take a bit of time to update the extension. I've taken the liberty of bundling the style from `markdown-it-myst/myst.css` (after prepending the jupyterlab markdown selector) and releasing on PyPI `0.1.1`.

In the long run, I am fully aware that we want this package to be published by the EB team, with the suggestion of using the ebp-bot. I can transfer ownership at a future time when we've set this up?

I would like to request some kind of admin rights on this repo so that I can merge PRs etc. Let me know if this is something you're amenable to?

**Comment by choldgraf** [comment]
@agoose77 - you've done much of the work in this repository already, and we've appreciated all of your contributions here (and elsewhere) over the months. I think you certainly deserve maintainer status. I've given you `maintain` rights to this repo 👍

**Comment by agoose77** [comment]
Fab, that was very quick - thanks!

**Comment by chrisjsewell** [comment]
Hey, @agoose77, yeh all help welcome thanks! (wanted also to circle round to chatting with you about the inline execution stuff)

So currently, this package pulls from markdown-it-myst, but actually that's not the most up-to-date at present. I/We have been working on  https://executablebooks.github.io/markdown-it-docutils/, which is a lot more powerful.

That package, and a few other, are used directly in: https://github.com/executablebooks/myst-vs-code/blob/master/src/extension.ts, to create https://marketplace.visualstudio.com/items?itemName=ExecutableBookProject.myst-highlight.

Ideally, the code in myst-vs-code would be "centralised" into an update to markdown-it-myst, and then essentially the VS Code extension and JupyterLab extension would very closely mirror each other (or indeed any other JavaScript implementation)

**Comment by agoose77** [comment]
Hey @chrisjsewell, thanks for the update. It seems at first glance that this is the directive-logic factored out into its own markdown-it plugin? Is the idea then that `markdown-it-myst` is just a meta-plugin that bundles this (and other non executable-books plugins) into a single `.use()` invocation?

**Comment by choldgraf** [comment]
I opened up https://github.com/executablebooks/jupyterlab-myst/issues/14 to track this

**Comment by chrisjsewell** [comment]
> Is the idea then that markdown-it-myst is just a meta-plugin that bundles this (and other non executable-books plugins) into a single .use() invocation?

pretty much yeh 👍

**Comment by agoose77** [comment]
OK. I'm going to close this issue then, because we do "have" a release on PyPI. I'll continue this discussion in #14?
