### ISSUE TITLE
Bounty 2000€ to get fullsupport of Myst-Markdown for jupyterbook in jupyter notebooks

### ISSUE THREAD

**Issue by MordicusEtCubitus** [executablebooks/jupyterlab-myst#55]
### Context

Hi, thanks for Jupyter Book and all the stuff around it.

I am writing a lot of documentation/training in my job using jupyter book.
I would like to get full support for Myst-Markdown/JupyterBook stuff when using a notebook, so it will be easiest to use the notebook in an usual way when it contains MystMarkdown. Actually the display is half of the time broken

For example, actually the dropdown option is not displayed properly in jupyter lab and not at all in jupyter, or the hide-input/output meta is not managed.

I know I can contribute to help implemented this, but I am suffering a huge lack of time. 

But my company is ready to pay a bounty of 2000€ to speed-up/help working on this
We just need a receipt.
Do you think this bounty can help getting more resources working on it or giving more of your time to speed-up the development of this extension ?

How do you want to be paid, redistribute the bounty ?

Thanks again,

With kind regards,

### Proposal

Speeding up the full support of jupyter book rendering in a running notebook

### Tasks and updates

For what is missing the most actually for us is:
- Full support of content blocks using the same theme as the default in jupyter book, so the rendering is the same when building the notebook
- Full support of dropdown and meta-tags to hide content
- Full support of tabs
- Full support of grid 

And finally, full support of all items in https://jupyterbook.org/en/stable/content/index.html
:)

**Comment by rowanc1** [comment]
Hi @MordicusEtCubitus -- thanks for the offer, coming around to this issues six months later! We have renewed efforts on the jupyterlab extension, and current efforts are taking shape in https://github.com/executablebooks/jupyterlab-mystjs, which will aimed to be merged in here in the future!

The most recent release, v0.1.3 supports tabs, grids, cards, admonition dropdowns. There is also improved support for cross-references through hover tooltips. Styling is close to JupyterBook, but based on new efforts in [mystjs](https://myst-tools.org/docs/mystjs).

We are planning to continue developing this over the coming months - if you are still working with MyST, we would love the feedback. From the financial bounty side, I did talk with @choldgraf about this when you posted and we felt we couldn't commit to actually following through 6 months ago - I think we are in a different place now! If the bounty is something you would still be interested in, let us know, I would suggest that this go to one of our financial hosts (e.g. 2i2c.org), and be distributed to team members (e.g. to support travel to a conference). Regardless of if that is still on the table, would love feedback on our new efforts!

**Comment by rowanc1** [comment]
Hi @MordicusEtCubitus -- the most recent release in v1.0.0 has many of the features you are looking for. I think the only outstanding piece is the `meta-tags` hiding content which potentially should be picked up as a "preview" pane of the notebook in a different tab? #82 has some follow on discussion there.

Happy to continue the conversation in those and other issues -- please let us know if your sponsorship offer is still open, as I think we are now in a position to execute on it! I am going to close the issue now, however, as I suspect the window on your side may have passed.

**Comment by MordicusEtCubitus** [comment]
Hi, sorry, I may have missed your message sent last week
Yes, I'm really interesting about this.
I will try it soon, maybe tonight
Yes I can pay the 2000€ bounty even if it is a bit late for I.

Let me try, and we will discuss how I can give the money, I just need a receipt

**Comment by rowanc1** [comment]
So cool! Can you send an email to rowan@curvenote.com and I will work with @choldgraf and @mmcky on the logistics. :)

Excited to get this extension to be top notch, and appreciate the help from you!!

**Comment by MordicusEtCubitus** [comment]
ok, no problem
but I will test tomorrow now, it is a bit late here now

**Comment by rowanc1** [comment]
You should use the latest version of `jupyterlab-myst` (this repo, no-js), it should be `v1.0.0`. The [release notes are here](https://github.com/executablebooks/jupyterlab-myst/releases/tag/v1.0.0).

**Comment by MordicusEtCubitus** [comment]
Hi,

My first issue was the dropdown style that was not correctly supported in jupyter lab, preventing my notebook to hide solution of exercices.
<pre>
  ````{admonition} Solution
  :class: tip, dropdown
      ```python
      ... code here ...
     ```
  ````
</pre>

This part is working now. And I like the new look which is clear and plainly (sobre in french)
  
I will test all markdown myst functionalities described in JupyterBook as soon as possible and provide feedback in issue tracker if it is ok for you.

But for tonight I am happy this that, so lets pay the bounty.

Sending an email to setup the process.

Thanks a lot !

**Comment by rowanc1** [comment]
Nice! That is super, I like the admonition dropdowns a lot:

![dropdown](https://user-images.githubusercontent.com/913249/218871775-ba74633c-99fc-4592-9bf6-0c130264435c.gif)

Yes, please keep the issues coming in, our aim is to fully support the directives in the base JupyterBook, of course this will take some time, as we are basically reimplementing sphinx. :)

**Comment by MordicusEtCubitus** [comment]
:)
How have you created this animated picture in github ? It appears to be a gif. Which tool have you used for that ?

**Comment by rowanc1** [comment]
I use [recordit](https://recordit.co/) for quick gifs like that!

**Comment by rowanc1** [comment]
Thank you again @MordicusEtCubitus for the donation -- this went to 2i2c and will be looked after by the @executablebooks/steering-council.

Please feel free to continue opening issues @MordicusEtCubitus, we will improve the extension as fast as we can!!
