### ISSUE TITLE
Fix github issue templates!

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/jupyterlab-myst#62]
We should change up the default templates, which are asking people to report jupyterlab versions.

**Comment by rowanc1** [comment]
I think @kolibril13 has a few ideas here! 🚀

**Comment by kolibril13** [comment]
@agoose77 , @rowanc1, I just made some experimentation here:

https://github.com/kolibril13/okapi/issues/new/choose
https://github.com/kolibril13/okapi/tree/main/.github/ISSUE_TEMPLATE

I think it would be nice if all user text could be in one cell, without fragmentation.
But as can be seen in this screen recording, the github forms approach result in very small cells, where not all content is displayed when opening the issue, in comparison to the classic .md issue templates: 

https://user-images.githubusercontent.com/44469195/227221159-4c55e0bd-444d-4fdb-aae2-3afd47aa2dd0.mov

**Comment by rowanc1** [comment]
Addressed in https://github.com/executablebooks/jupyterlab-myst/pull/131
