### ISSUE TITLE
Clickable check lists

### ISSUE THREAD

**Issue by nthiery** [executablebooks/jupyterlab-myst#63]
### Context

In my student assignments, I include a checklist so that student can
check tasks as they are achieved to keep track of their progress through
the assignment. For now, they have to edit the underlying markdown
(double click, and replace `- [ ]` by `- [x]`) which is inconvenient and
error-prone.

### Proposal

When a rendered markdown cell contains a check-list, enable to
check/uncheck a checkbox by a simple click in the check-box. Like
e.g. in github/gitlab issue trackers.

Note: this involves not only rendering of cells, but also editing
the underlying markdown. So this may well be out of scope of
jupyterlab-mystjs and/or may require coordination with the
progress with
[prosemirror wysiwig cell editor](https://github.com/jupyterlab/jupyterlab/issues/5908).

Bonus: enable markdown cells that are read-only but for
checking/unchecking check boxes. This would require a
third value to the `editable` cell option: 
non editable/checkable/editable, a change which goes even
further away of jupyterlab-mystjs.

**Comment by rowanc1** [comment]
Related to https://github.com/executablebooks/mystjs/issues/244

**Comment by rowanc1** [comment]
Here is the current version @nthiery @agoose77:

![tasklists-in-jupyterlab tsx](https://user-images.githubusercontent.com/913249/226813767-4fe8238a-af63-492d-bcc7-57e973bf86c3.gif)

Let me know your thoughts, I think it is pretty cool. :)

**Comment by nthiery** [comment]
Nice!!! Can't wait to try it out :-)

**Comment by agoose77** [comment]
Closed by #121
