### ISSUE TITLE
Support additional directives (tabs, grids, citations)

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/jupyterlab-myst#70]
There are a number of directives/roles that are possible through the command line mystjs interface (grids, tabs, citations, etc.) that would be good to have in the default jupyterlab experience.

This will likely need a bit of revisiting on the organization of the existing code -- we will keep some running thoughts here as we pull things out for reuse!

- [x] tabs, grids, cards
- [ ] citations

**Comment by agoose77** [comment]
@rowanc1 I noticed that the grid doesn't seem to be reactive

**Comment by rowanc1** [comment]
Citations are starting to be parsed in #88, still need to hook up the transforms properly, that will take a bit more work and we need to know where the bibtex file is!

**Comment by rowanc1** [comment]
Closing this issue in favour of #127, which is specific to the citation work.
