### ISSUE TITLE
Use new markdown-it plugins

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/jupyterlab-myst#8]
Essentially, this plugin should eventually mirror: https://github.com/executablebooks/myst-vs-code/blob/master/src/extension.ts

A few things to consider here:

1. We want configuration to enable MyST syntax extensions; this should be easy to achieve here
2. the VS extension allows loading the CSS provided by markdown-it-docutils: https://github.com/executablebooks/myst-vs-code/blob/c8c96542171ebe6ccdd896cf8337a5ffffeb73d4/package.json#L115. Can we achieve that here

cc @agoose77

**Comment by chrisjsewell** [comment]
and yeh, as I've just mention on a jupyter thread, you can check out some of the plugin rendering at:

- https://executablebooks.github.io/markdown-it-docutils
- https://executablebooks.github.io/markdown-it-amsmath
- https://executablebooks.github.io/markdown-it-dollarmath

**Comment by chrisjsewell** [comment]
Also to note, there is still activity going on around these plugins: https://github.com/executablebooks/meta/issues/449

**Comment by rowanc1** [comment]
Once some more of those are merged in we can merge executablebooks/markdown-it-myst#33 and then this package can consume the updates with a version bump. I think it is worth combining and having a myst-specific export (which this package is meant for).

I am planning on getting back to the PRs that you reviewed last week today or tomorrow.

**Comment by chrisjsewell** [comment]
Yep indeed 👍 just wanted to make @agoose77 of the changes, and start thinking about the config/css points

**Comment by agoose77** [comment]
Appreciate it all, I'm following this remotely!

**Comment by agoose77** [comment]
So, it seems to me that we have the following top-level plugins that we need to expose/require as jupyterlab-markup plugins:
- [ ] `markdown-it-front-matter`
- [x] `markdown-it-footnote`\*
- [ ] `markdown-it-docutils`
- [ ] `markdown-it-dollarmath`
- [ ] `markdown-it-amsmath`
- [x] `markdown-it-deflist`\*
- [x] `markdown-it-task-lists`\*

\* already provided by `jupyterlab-markup`

**Comment by chrisjsewell** [comment]
Yep, plus there are some small plugins currently directly implemented in https://github.com/executablebooks/myst-vs-code/blob/master/src/mdPlugins.ts

**Comment by agoose77** [comment]
Could we move that inline plugin into a new / existing package(s)?

**Comment by chrisjsewell** [comment]
most certainly, this is where I was thinking markdown-it-myst might come in useful

**Comment by agoose77** [comment]
Ah OK. I'm not 100% confident with the entire MyST landscape yet, so I'm not clear on where everything goes. In my head, I envisage `markdown-it-myst` being an empty meta-package that just depends upon the building blocks of a MyST Markdown variant. In that case, it would perhaps be ideal if this small `mdPlugins` belonged to the "another" `markdown-it-myst-extras` package?

**Comment by chrisjsewell** [comment]
> it would perhaps be ideal if this small mdPlugins belonged to the "another" markdown-it-myst-extras package?

Ask and you shall receive 😉 
https://github.com/executablebooks/markdown-it-myst-extras
