### ISSUE TITLE
Create a 1:1 mapping from `markdown-it` plugin to `jupyterlab-markup` plugin

### ISSUE THREAD

**Issue by agoose77** [executablebooks/jupyterlab-myst#9]
### Description / Summary

Currently this extension installs an opinionated set of plugins. I think we should split this up into multiple JupyterLab extensions (one `simpleMarkdownItPlugin` per `markdown-it` plugin). 

### Value / benefit

This will allow users to customize things whilst still delivering all of the extensions in a single Python package.

### Tasks to complete

- [ ] `roles`
- [ ] `blocks`
- [ ] `directives`

**Comment by chrisjsewell** [comment]
Could you explain this a little further? (I haven’t had the chance to check out JupyterLab-markup just yet)

Where possible, I would like to have parity between the configuration they have in myst-parser (https://myst-parser.readthedocs.io/en/latest/sphinx/reference.html), at least in how extensions are activated. 

For example, if n the vs code extension they can set these in the settings.json. See https://github.com/executablebooks/myst-vs-code#preview-enhancement, and the actual schema: https://github.com/executablebooks/myst-vs-code/blob/c8c96542171ebe6ccdd896cf8337a5ffffeb73d4/package.json#L125

**Comment by chrisjsewell** [comment]
Just to give you some insight: my ultimate goal would be to introduce LSP features for the language, like autocompletions which are already available in the vs code extension, and reference lookups, like I’ve previously prototyped in https://github.com/chrisjsewell/rst-language-server

**Comment by chrisjsewell** [comment]
Obviously https://github.com/krassowski/jupyterlab-lsp, may be able to facilitate something like this 🤔

**Comment by agoose77** [comment]
Sure! `jupyterlab-markup` creates the canonical `markdown-it` renderer. Other JupyterLab extensions can then declare `markdown-it` plugins by using the JupyterLab dependency injection to obtain a reference to the `jupyterlab-markup` plugin manager. 
`jupyterlab-markup` allows the user to disable plugins and override settings from the JupyterLab UI, but only if you register each plugin separately. There are different ways to register a plugin, but one of the simpler ones is to use the `simpleMarkdownItPlugin` convenience method that creates one JupyterLab extension for a `markdown-it` plugin.

Alternatively, you can create a `JupyterFrontEndPlugin` and call `markdownIt.addPluginProvider` for each plugin you wish to add, but it's simpler just to use `simpleMarkdownItPlugin`.

**Comment by agoose77** [comment]
> Obviously https://github.com/krassowski/jupyterlab-lsp, may be able to facilitate something like this

Hehe, there is a bit of a similar discussion happening with @bollwyvl in this space as well, maybe he can chime in too!

**Comment by chrisjsewell** [comment]
Sure ting, I’ve certainly got a lot of ideas on this. One annoyance actually with markdown-it is that I found it great for everything (performance, extensibility, ...) except there is no built-in way to retrieve the exact line+character location of each syntax token (see https://github.com/markdown-it/markdown-it/issues/336#issuecomment-841759552), which is quite important for LSP applications 😬
