### ISSUE TITLE
Update interactive examples with f-strings

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/jupyterlab-myst#94]
``That's {eval}`f"{pc:0.1f}"`% of your recommended daily calories.``

From @fperez giving me #PythonTips over slack. Thank you! :)

![image](https://user-images.githubusercontent.com/913249/221326878-dc5cf626-3f85-4736-af5a-060aadfe499b.png)

**Comment by fperez** [comment]
Closing - [this commit](https://github.com/executablebooks/jupyterlab-myst/commit/ec3dd630bf05a83f2e77859f82f1fd069f26856b) should have referenced this issue - I made a typo and said #96 by accident.
