### ISSUE TITLE
Inline YouTubeVideos don't render when notebook is not `trusted`

### ISSUE THREAD

**Issue by fperez** [executablebooks/jupyterlab-myst#97]
### Describe the bug

**context**
In `IPython.display` we have a built-in `YouTubeVideo` object that's very handy. 

For example, this code

```python
from IPython.display import YouTubeVideo
YouTubeVideo('NxSNVt9XsCI')
```

produces an embedded video

![image](https://user-images.githubusercontent.com/57394/221346138-c0852f49-7052-4f22-9ea0-df0007a5b569.png)

**expectation**
This should also work in our mardkown cells...

**bug**
Nothing is rendered. I've marked it in the inline example notebook, which we can update once this is fixed.

### Reproduce the bug

See above.

**Comment by rowanc1** [comment]
Thanks @fperez. I did just fix a bug here which may be related:
- https://github.com/executablebooks/myst-theme/pull/23
That is _not_ yet picked up in v1.1.0.

Some of the inline renderers also have zero height (e.g. altair), so we may need to do more CSS work here.

**Comment by fperez** [comment]
Awesome, thx a lot @rowanc1  - this isn't urgent, I just caught it yesterday as I was experimenting and updating the docs. Glad to hear there's a fix coming :)

**Comment by fperez** [comment]
Note though that I just tried trusting the notebook first and then running it all again (on binder), and I still don't see that video rendering... Am I doing something wrong?

**Comment by agoose77** [comment]
It's working for me:
- <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd> 
- Type `"Trust Notebook"` 
- Execute the command
- Restart & run all cells

**Comment by rowanc1** [comment]
Also worked for me -- I am not sure why, but the `YouTubeVideo` evaluation in the output cell seemed to hang for ~10 seconds on binder. I don't think that we are in that code path at all.

**Comment by fperez** [comment]
Weird, not for me... This is a binder that I trusted (see badge at bottom) right at opening, and ran in full:

![image](https://user-images.githubusercontent.com/57394/221684017-f8c19c96-ed43-4f86-9b91-7d391dc97e39.png)

No dice. Odd...

Gotta focus on teaching now, will test again later.

**Comment by fperez** [comment]
> I am not sure why, but the `YouTubeVideo` evaluation in the output cell seemed to hang for ~10 seconds on binder. I don't think that we are in that code path at all.

Same for me - I wonder if it's a security thing on binder?

**Comment by rowanc1** [comment]
Just to be clear, you do need to that the eval out of the code block, right now it is rendering as code!

**Comment by agoose77** [comment]
@fperez did you add the ``{eval}`...` `` code anywhere to embed the video? It's not present by default.

**Comment by agoose77** [comment]
@rowanc1 jinx ;)

**Comment by fperez** [comment]
🤦 ^ 💯 

NVM, I'll go teach a class instead 😉

**Comment by fperez** [comment]
I meant to test the code in the markdown that had `ytlink` to also embed an actual video, I tested that at first and it didn't work, and after the fix I forgot to change it again...

More ☕ for this table, please.

**Comment by fperez** [comment]
Mmmh, weird. It blinked and appeared for a second, then it disappeared, leaving vertical whitespace instead:

![image](https://user-images.githubusercontent.com/57394/221686416-d860e375-7f29-4d08-a9a1-a3cbcfbd27d0.png)

**Comment by fperez** [comment]
This is on binder... And about 30s later, it reappeared! No idea why... I'll leave figuring that out to you folks :)
